corpora:
    #mann-ki-baat-test:
    #    splits : ['test']
    #    langs : ['hi','en']
    #ilci_pa:
    #    splits: ['train','test','dev']
    #     # langs: [ 'en', 'hi',  'ta', 'te', 'ml', 'ur', 'bn']
    #    langs: ['en', 'pa']
     #   langs: ['en', 'hi']
        # wat-ilmpc:
        # wat-splits: ['dev']
        # wat-langs: ['en', 'ta']
    #iitb-hi-en:
    #    splits: ['train', 'dev', 'test']
    #    langs: ['en', 'hi']
    #iitb-hi-en-bt:
    #    splits: ['train', 'dev', 'test']
    #    langs: ['en', 'hi']
    #wat-ilmpc:
    #     #splits: ['train', 'dev', 'test']
    #     splits: ['train']
    #     # langs: [ 'en', 'hi',  'ta', 'te', 'ml', 'ur', 'bn']
    #     langs: ['en','bn']
    #national-newscrawl:
    #     splits: ['train']
    #     langs: ['en', 'or']
    #ufal-en-tam:
    #    splits: ['train']
    #    langs: ['en', 'pa']
    #monolingual:
    #    splits: ['train']
    #    langs: ['en','pa']
    #odi-en-corp1.0:
    #    splits: ['train','dev','test']
    #    langs: ['en','or']
dictionary:
    src: '/content/ilmulti/resources/fairseq-dictionaries/ilmulti-v1.dict.txt'
    tgt: '/content/ilmulti/resources/fairseq-dictionaries/ilmulti-v1.dict.txt'
