corpora:
    iitb-hi-en:
         splits: ['test']
         langs: ['en', 'hi']
    ilci:
         splits: ['test']
         langs: [ 'en', 'hi', 'ta', 'te', 'ml', 'ur', 'bn', 'gu', 'mr', 'pa']
    wat-ilmpc:
         splits: ['test']
         langs: [ 'en', 'hi',  'ta', 'te', 'ml', 'ur', 'bn']
    ufal-en-tam:
         splits: ['test']
         langs: ['en', 'ta']
    bible-en-te:
         splits: ['test']
         langs: ['en', 'te']
    odiencorp:
         splits: ['test']
         langs: ['en','or']
    newstest2019guen:
        splits: ['test']
        langs: ['en', 'gu']
    newstest2019engu:
        splits: ['test']
        langs: ['en', 'gu']

    # pib-test:
    #     splits: ['test']
    #     langs: ['en', 'hi', 'ta', 'te', 'ml', 'ur', 'bn', 'gu', 'mr', 'pa', 'or']

direction:
    src: 'xx'
    tgt: 'en'

dictionary:
    src: '/home/shashanks/ilmulti/ilmulti/sentencepiece/central.dict'
    tgt: '/home/shashanks/ilmulti/ilmulti/sentencepiece/central.dict'
